stages:
- build

build-core:
  stage: build
  script:
   - echo %USERDOMAIN%\%USERNAME%
   - SET
   - echo %CI_PROJECT_DIR%
   - call %CI_PROJECT_DIR%/.gitlab-scripts/init-deps-code.cmd
   - call %CI_PROJECT_DIR%/.gitlab-scripts/build-projects-core.cmd
   - call %CI_PROJECT_DIR%/.gitlab-scripts/test-projects-core.cmd
  tags:
    - windows

