stages:
- build

build-core:
  stage: build
  script:
   - echo %USERDOMAIN%\%USERNAME%
   - SET
   - echo %CI_PROJECT_DIR%
   - call .gitlab-scripts/init-deps-core.cmd
   - call .gitlab-scripts/build-projects-core.cmd
   - call .gitlab-scripts/test-projects-core.cmd
  tags:
    - windows
  when: manual

build-native:
  stage: build
  script:
   - echo %USERDOMAIN%\%USERNAME%
   - SET
   - echo %CI_PROJECT_DIR%
   - call .gitlab-scripts/build-projects-native.cmd
   - call .gitlab-scripts/test-projects-native.cmd
  tags:
    - windows



