stages:
- build

build-core:
  stage: build
  script:
   - echo %USERDOMAIN%\%USERNAME%
   - SET
   - .gitlab-scripts/init-deps-code.cmd
   - .gitlab-scripts/build-projects-core.cmd
   - .gitlab-scripts/test-projects-core.cmd
  tags:
    - windows

