stages:
- build

build-core:
  stage: build
  script:
   - echo %USERDOMAIN%\%USERNAME%
   - SET
   - echo %CI_PROJECT_DIR%
   - call .gitlab-scripts/init-deps-core.cmd
   - call .gitlab-scripts/build-projects-core.cmd
   - call .gitlab-scripts/test-projects-core.cmd
  tags:
    - windows
  when: manual

build-native:
  stage: build
  script:
   - echo %USERDOMAIN%\%USERNAME%
   - SET
   - echo %CI_PROJECT_DIR%
   - call .gitlab-scripts/build-projects-native.cmd
   - call .gitlab-scripts/test-projects-native.cmd
   - call .gitlab-scripts/prepare-artifacts.cmd
  tags:
    - windows
  artifacts:
    expire_in: 1 week
    paths:
    - OUTCOME
    reports:
      junit:
        - test\\Datadog.Trace.ClrProfiler.Native.Tests\\bin\\Release\\\x64\test*.xml
        - test\\Datadog.Trace.ClrProfiler.Native.Tests\\bin\\Release\\\x86\test*.xml