version: '3'
services:
  datadog-agent:
    image: datadog/agent:latest
    environment:
    - DD_API_KEY=${DD_API_KEY}
    - DD_ENV=${DD_ENV}
    - DD_APM_ENABLED=true
    - DD_APM_NON_LOCAL_TRAFFIC=true
    - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
  app-none:
    depends_on:
    - datadog-agent
    image: app-none
    build:
      context: ../
      dockerfile: performance/AspNetCore31/Dockerfile
      args:
      - DD_TRACER_VERSION=project
    environment:
    - DD_AGENT_HOST=datadog-agent
    - DD_SERVICE_NAME=app-none
    - DD_TRACER_VERSION=project
    ports:
    - "127.0.0.1:60000:80"
  app-nuget:
    depends_on:
    - datadog-agent
    image: app-manual-${TRACER_NUGET_VERSION}
    build:
      context: ../
      dockerfile: performance/AspNetCore31/Dockerfile
      args:
      - DD_TRACER_VERSION=${TRACER_NUGET_VERSION}
    environment:
    - DD_AGENT_HOST=datadog-agent
    - DD_SERVICE_NAME=app-manual-1-${TRACER_NUGET_VERSION}
    - DD_TRACER_VERSION=${TRACER_NUGET_VERSION}
    - DD_MANUAL_SPAN_COUNT=1
    ports:
    - "127.0.0.1:60001:80"
  app-nuget-more-spans:
    depends_on:
    - datadog-agent
    image: app-manual-${TRACER_NUGET_VERSION}
    build:
      context: ../
      dockerfile: performance/AspNetCore31/Dockerfile
      args:
      - DD_TRACER_VERSION=${TRACER_NUGET_VERSION}
    environment:
    - DD_AGENT_HOST=datadog-agent
    - DD_SERVICE_NAME=app-manual-${MANUAL_SPAN_COUNT}-${TRACER_NUGET_VERSION}
    - DD_TRACER_VERSION=${TRACER_NUGET_VERSION}
    - DD_MANUAL_SPAN_COUNT=${MANUAL_SPAN_COUNT}
    ports:
    - "127.0.0.1:60002:80"
  app-project:
    depends_on:
    - datadog-agent
    image: app-manual-latest
    build:
      context: ../
      dockerfile: performance/AspNetCore31/Dockerfile
      args:
      - DD_TRACER_VERSION=project
    environment:
    - DD_AGENT_HOST=datadog-agent
    - DD_SERVICE_NAME=app-manual-1-latest
    - DD_TRACER_VERSION=project
    - DD_MANUAL_SPAN_COUNT=1
    ports:
    - "127.0.0.1:60003:80"
  app-project-more-spans:
    depends_on:
    - datadog-agent
    image: app-manual-latest
    build:
      context: ../
      dockerfile: performance/AspNetCore31/Dockerfile
      args:
      - DD_TRACER_VERSION=project
    environment:
    - DD_AGENT_HOST=datadog-agent
    - DD_SERVICE_NAME=app-manual-${MANUAL_SPAN_COUNT}-latest
    - DD_TRACER_VERSION=project
    - DD_MANUAL_SPAN_COUNT=${MANUAL_SPAN_COUNT}
    ports:
    - "127.0.0.1:60004:80"
#  app-profiler:
#    depends_on:
#    - datadog-agent
#    image: app-with-profiler
#    build:
#      context: ../
#      dockerfile: performance/AspNetCore31/Dockerfile
#    environment:
#    - DD_SERVICE_NAME=app-with-profiler
#    - DD_AGENT_HOST=datadog-agent
#    - DD_TRACER_VERSION=${TRACER_NUGET_VERSION}
#    - DD_MANUAL_SPAN_COUNT=${MANUAL_SPAN_COUNT}
#    - CORECLR_ENABLE_PROFILING=1
#    ports:
#    - "127.0.0.1:60005:80"
  http-requests:
    depends_on:
    - app-none
    - app-nuget
    - app-project
    image: http-requests
    build:
      context: http-requests/
    command: "dotnet http-requests.dll http://app-none:80 http://app-nuget:80 http://app-nuget-more-spans:80 http://app-project:80 http://app-project-more-spans:80 --rps ${RPS}"
